# Generated by Django 4.2.2 on 2023-12-22 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DreamedJobAI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                ("created", models.IntegerField()),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("consent", models.CharField(max_length=10, null=True)),
                ("customer_country", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=100)),
                ("payment_status", models.CharField(max_length=100)),
                ("item_description", models.CharField(max_length=100)),
                ("item_id", models.CharField(max_length=100)),
                ("price_id", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
