# Generated by Django 4.2.2 on 2023-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0002_stripecheckout"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecheckout",
            name="repeated_order",
            field=models.IntegerField(default=0),
        ),
    ]
