# Generated by Django 4.2.2 on 2023-12-22 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0003_stripecheckout_repeated_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripecheckout",
            name="repeated_order",
        ),
        migrations.RemoveField(
            model_name="stripecheckout",
            name="user",
        ),
    ]
