# Generated by Django 4.2.2 on 2023-12-23 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0006_usertokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertokens",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 23, 0, 28, 35, 759880, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
