# Generated by Django 4.2.2 on 2023-12-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0007_alter_usertokens_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertokens",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
