# Generated by Django 4.2.2 on 2024-01-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "DreamedJobAI",
            "0011_blogpost_author_blogpost_author_pp_blogpost_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="suitablejobs",
            name="optimized_cv",
            field=models.FileField(blank=True, null=True, upload_to="optimized_cv/"),
        ),
    ]
