# Generated by Django 4.2.2 on 2024-01-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0013_suitablejobs_feedback_suitablejobs_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitablejobs",
            name="applied",
            field=models.BooleanField(default=False),
        ),
    ]
