# Generated by Django 4.2.2 on 2024-01-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0014_suitablejobs_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitablejobs",
            name="interview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suitablejobs",
            name="offer",
            field=models.BooleanField(default=False),
        ),
    ]
