# Generated by Django 4.2.2 on 2024-01-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0015_suitablejobs_interview_suitablejobs_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitablejobs",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
