# Generated by Django 4.2.2 on 2024-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0019_seenjobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercv",
            name="skills",
            field=models.CharField(null=True),
        ),
    ]
