# Generated by Django 4.2.2 on 2024-02-01 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DreamedJobAI", "0020_usercv_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceLevelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("1-3", "1-3 years of experience"),
                            ("4-7", "4-7 years of experience"),
                            ("8+", "8+ years of experience"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
